

const projects = [
  {
    description: "HopeFM is a public audio platform of Sound of Hope Media Group (SOH). It has been dedicated to providing truthful and accurate news, and high-valued lifestyle information to the public. SOH is a 501(c)(3) non-profit organization registered with the State of California.",
    title: "HopeFM",
    github: "",
    stack: ["React" , "Redux",  "Node js", "Express js", "Sql"],
    url: "https://thehope.fm/",
    image: "https://tanypatil98.github.io/Portfolio/images/project-11.png",
    index: 0,
    slug: "HopeFM",
  }, {
    description: "Trendage is a Machine Learning & retail data company solving apparel ecommerce discovery, tagging and recommendations. their solutions are enabling leading retailers and brands to increase their average order values, conversions and improve shopper experience.",
    title: "Fashion Apparel (By Trendage)",
    github: "",
    stack: ["React", "Es6", "Redux", "Fabric js"],
    url: "https://www.trendage.com/",
    image: "https://tanypatil98.github.io/Portfolio/images/project-2.png",
    index: 1,
    slug: "fashionApparel",
  }, {
    description: "Priceline.com is an online travel agency for finding discount rates for travel-related purchases such as airline tickets and hotel stays. The company facilitates the provision of travel services from its suppliers to its clients.",
    title: "PriceLine",
    github: "",
    stack: ["React", "Es6", "Redux"],
    url: "http://www.priceline.com/",
    image: "	https://tanypatil98.github.io/Portfolio/images/project-33.png",
    index: 2,
    slug: "travelsite",
  }, {
    description: "AMI -Asset Management Interface is a Ab-Inbev Project manage There asset verification process. It involves following tasks Checking Verified and To be Verified Assets, Fetching user’s Assets for approving action on it by the Fa, Assigning Assets to another user and Sub user By the Fa and User only, Sending Email to user for not verified assets.",
    title: "AMi-Asset Management Interface",
    github: "",
    stack: ["React" , "Redux",  "Node js", "Express js", "Sql"],
    url: "https://ami.ab-inbev.com/",
    image: "https://tanypatil98.github.io/Portfolio/images/project-4.png",
    index: 3,
    slug: "assetManagement",
  }, {
    description: "It is the web portfolio created using gatsby js.",
    title: "Portfolio",
    github: "https://github.com/Tanypatil98/PortfolioWeb",
    stack: ["Html", "Css", "React", "Gatsby.Js", "GraphQl"],
    url: "https://tanaypatil.netlify.app/",
    image: "https://tanypatil98.github.io/Portfolio/images/project-5.png",
    index: 4,
    slug: "portfolio",
  }, {
    description: "NAZ ATR MJE Automatic Parking Solution. It involves following tasks Checking Parking And Unpark request, There is two roles one is requester and another one is reviewer, Requester request the file which he/she want to parked. And also this process is done by three steps, Reviewer Review the status and other details of the requesters request.",
    title: "NAZ ATR MJE Automatic Parking Solution",
    github: "",
    stack: ["React" , "Redux",  "Node js", "Express js", "Sql"],
    url: "https://acoemjeappnaz.azurewebsites.net/",
    image: "https://tanypatil98.github.io/Portfolio/images/project-6.png",
    index: 5,
    slug: "parkingSolution",
  }, {
    description: "With DriveChat you can now easily get in touch with other road users.It does not matter whether it is a car, a motorcycle or a truck. Just create a profile and add your license plate to your profile.",
    title: "DriveChat",
    github: "",
    stack: ["React" , "Redux",  "React Native", "Firebase", "Social login"],
    url: "",
    image: "https://tanypatil98.github.io/Portfolio/images/unnamed.png",
    index: 6,
    slug: "driveChat",
  },{
    description: "Iensure is an application that helps the end user to keep track of multiple insurance policies and it makes the claim process easier and smoother with just one click. One can get all the health card details and submit the inquiries based on the selected insurance, be it Vehicle insurance, Health insurance, Travel insurance, and any other.",
    title: "iensure",
    github: "",
    stack: ["React" , "Redux",  "React Native", "Firebase", "Social login"],
    url: "",
    image: "https://tanypatil98.github.io/Portfolio/images/unnamed (1).png",
    index: 7,
    slug: "insurance",
  }]

export default projects
